import type { BankAccount, Terminal } from "./types";

export const MOCK_BANK_ACCOUNTS: BankAccount[] = [
  { id: "ba_1", bankName: "Al Baraka Bank", accountLast4: "4821" },
  { id: "ba_2", bankName: "CPA", accountLast4: "9014" },
  { id: "ba_3", bankName: "BNA", accountLast4: "1732" },
];

export const MOCK_TERMINALS: Terminal[] = [
  {
    id: "t_1",
    code: "VTPE-28491",
    label: "Store Downtown",
    category: "classic",
    paymentVolume: 284500,
    qrCodeCount: 3,
    settlementType: "balance",
    status: "active",
    createdAt: "2026-06-02T10:00:00Z",
    lastActivityAt: "2 min ago",
  },
  {
    id: "t_2",
    code: "VTPE-19832",
    label: "Store Bab Ezzouar",
    category: "classic",
    paymentVolume: 148200,
    qrCodeCount: 1,
    settlementType: "existing_bank_account",
    bankAccount: MOCK_BANK_ACCOUNTS[1],
    status: "active",
    createdAt: "2026-05-11T10:00:00Z",
    lastActivityAt: "18 min ago",
  },
  {
    id: "t_3",
    code: "VTPE-7266",
    label: "Terminal 7266",
    category: "classic",
    paymentVolume: 0,
    qrCodeCount: 0,
    settlementType: "balance",
    status: "pending",
    createdAt: "2026-09-18T10:00:00Z",
  },
  {
    id: "t_4",
    code: "VTPE-11234",
    label: "Algiers Center",
    category: "business",
    paymentVolume: 512800,
    qrCodeCount: 5,
    settlementType: "existing_bank_account",
    bankAccount: MOCK_BANK_ACCOUNTS[0],
    status: "active",
    createdAt: "2026-03-20T10:00:00Z",
    lastActivityAt: "5 min ago",
  },
  {
    id: "t_5",
    code: "VTPE-99812",
    label: "Oran Store",
    category: "classic",
    paymentVolume: 98400,
    qrCodeCount: 2,
    settlementType: "balance",
    status: "active",
    createdAt: "2026-04-14T10:00:00Z",
    lastActivityAt: "12 min ago",
  },
  {
    id: "t_6",
    code: "VTPE-55421",
    label: "Constantine",
    category: "business",
    paymentVolume: 760300,
    qrCodeCount: 8,
    settlementType: "existing_bank_account",
    bankAccount: MOCK_BANK_ACCOUNTS[2],
    status: "active",
    createdAt: "2026-02-08T10:00:00Z",
    lastActivityAt: "28 min ago",
  },
  {
    id: "t_7",
    code: "VTPE-44321",
    label: "Tipaza Store",
    category: "classic",
    paymentVolume: 42700,
    qrCodeCount: 1,
    settlementType: "balance",
    status: "disabled",
    createdAt: "2026-01-30T10:00:00Z",
    lastActivityAt: "2 hours ago",
  },
  {
    id: "t_8",
    code: "VTPE-33210",
    label: "Setif Branch",
    category: "classic",
    paymentVolume: 221600,
    qrCodeCount: 4,
    settlementType: "existing_bank_account",
    bankAccount: MOCK_BANK_ACCOUNTS[1],
    status: "active",
    createdAt: "2026-05-29T10:00:00Z",
    lastActivityAt: "1 hour ago",
  },
  {
    id: "t_9",
    code: "VTPE-60117",
    label: "Blida Kiosk",
    category: "classic",
    paymentVolume: 63200,
    qrCodeCount: 1,
    settlementType: "balance",
    status: "active",
    createdAt: "2026-07-09T10:00:00Z",
    lastActivityAt: "40 min ago",
  },
  {
    id: "t_10",
    code: "VTPE-72301",
    label: "Annaba Waterfront",
    category: "business",
    paymentVolume: 389100,
    qrCodeCount: 6,
    settlementType: "existing_bank_account",
    bankAccount: MOCK_BANK_ACCOUNTS[0],
    status: "active",
    createdAt: "2026-03-02T10:00:00Z",
    lastActivityAt: "1 hour ago",
  },
  {
    id: "t_11",
    code: "VTPE-88452",
    label: "Batna Central",
    category: "classic",
    paymentVolume: 175400,
    qrCodeCount: 3,
    settlementType: "balance",
    status: "active",
    createdAt: "2026-06-21T10:00:00Z",
    lastActivityAt: "3 hours ago",
  },
  {
    id: "t_12",
    code: "VTPE-90213",
    label: "Djelfa Express",
    category: "classic",
    paymentVolume: 0,
    qrCodeCount: 0,
    settlementType: "balance",
    status: "pending",
    createdAt: "2026-09-15T10:00:00Z",
  },
  {
    id: "t_13",
    code: "VTPE-10982",
    label: "Sidi Bel Abbes",
    category: "classic",
    paymentVolume: 54900,
    qrCodeCount: 2,
    settlementType: "existing_bank_account",
    bankAccount: MOCK_BANK_ACCOUNTS[2],
    status: "disabled",
    createdAt: "2026-01-12T10:00:00Z",
    lastActivityAt: "3 days ago",
  },
  {
    id: "t_14",
    code: "VTPE-40218",
    label: "Mostaganem Plaza",
    category: "business",
    paymentVolume: 445700,
    qrCodeCount: 7,
    settlementType: "balance",
    status: "active",
    createdAt: "2026-04-27T10:00:00Z",
    lastActivityAt: "6 hours ago",
  },
  {
    id: "t_15",
    code: "VTPE-55873",
    label: "Ouargla Outlet",
    category: "classic",
    paymentVolume: 31200,
    qrCodeCount: 1,
    settlementType: "balance",
    status: "pending",
    createdAt: "2026-09-10T10:00:00Z",
  },
  {
    id: "t_16",
    code: "VTPE-66129",
    label: "Skikda Port",
    category: "classic",
    paymentVolume: 128900,
    qrCodeCount: 2,
    settlementType: "existing_bank_account",
    bankAccount: MOCK_BANK_ACCOUNTS[1],
    status: "active",
    createdAt: "2026-05-05T10:00:00Z",
    lastActivityAt: "9 hours ago",
  },
  {
    id: "t_17",
    code: "VTPE-77340",
    label: "Bejaia Marina",
    category: "business",
    paymentVolume: 592300,
    qrCodeCount: 9,
    settlementType: "existing_bank_account",
    bankAccount: MOCK_BANK_ACCOUNTS[0],
    status: "active",
    createdAt: "2026-02-19T10:00:00Z",
    lastActivityAt: "11 hours ago",
  },
  {
    id: "t_18",
    code: "VTPE-83201",
    label: "Tlemcen Souk",
    category: "classic",
    paymentVolume: 76400,
    qrCodeCount: 2,
    settlementType: "balance",
    status: "active",
    createdAt: "2026-06-30T10:00:00Z",
    lastActivityAt: "14 hours ago",
  },
  {
    id: "t_19",
    code: "VTPE-91002",
    label: "Chlef Junction",
    category: "classic",
    paymentVolume: 19800,
    qrCodeCount: 1,
    settlementType: "balance",
    status: "disabled",
    createdAt: "2026-01-04T10:00:00Z",
    lastActivityAt: "5 days ago",
  },
  {
    id: "t_20",
    code: "VTPE-30044",
    label: "Ghardaia Market",
    category: "classic",
    paymentVolume: 41300,
    qrCodeCount: 1,
    settlementType: "existing_bank_account",
    bankAccount: MOCK_BANK_ACCOUNTS[2],
    status: "active",
    createdAt: "2026-07-22T10:00:00Z",
    lastActivityAt: "20 hours ago",
  },
  {
    id: "t_21",
    code: "VTPE-48810",
    label: "Laghouat Depot",
    category: "classic",
    paymentVolume: 12600,
    qrCodeCount: 0,
    settlementType: "balance",
    status: "pending",
    createdAt: "2026-09-05T10:00:00Z",
  },
  {
    id: "t_22",
    code: "VTPE-59023",
    label: "Relizane Hub",
    category: "business",
    paymentVolume: 321900,
    qrCodeCount: 5,
    settlementType: "balance",
    status: "active",
    createdAt: "2026-03-14T10:00:00Z",
    lastActivityAt: "1 day ago",
  },
  {
    id: "t_23",
    code: "VTPE-67781",
    label: "Biskra Terminal",
    category: "classic",
    paymentVolume: 88700,
    qrCodeCount: 2,
    settlementType: "existing_bank_account",
    bankAccount: MOCK_BANK_ACCOUNTS[1],
    status: "active",
    createdAt: "2026-04-08T10:00:00Z",
    lastActivityAt: "2 days ago",
  },
  {
    id: "t_24",
    code: "VTPE-71455",
    label: "El Oued Point",
    category: "classic",
    paymentVolume: 27100,
    qrCodeCount: 1,
    settlementType: "balance",
    status: "active",
    createdAt: "2026-06-11T10:00:00Z",
    lastActivityAt: "3 days ago",
  },
];
